name: CMake

on:
  pull_request:
    branches: [ v2.4.0-devel ]

env:
  BUILD_TYPE: Release

jobs:
  functional_and_mem_tests:
    # runs-on: ubuntu:21.10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install needed libs
      run: sudo apt update && sudo apt install -y cmake build-essential libmpfr-dev valgrind

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: make -C ${{github.workspace}}/build -j

    - name: Functional tests
      working-directory: ${{github.workspace}}/test
      run: ${{github.workspace}}/build/rpn \"all.md\" test

    - name: Memory tests
      working-directory: ${{github.workspace}}/test
      run: ./mem_test.sh ${{github.workspace}}/build/rpn
